### ISSUE TITLE
README看不懂，希望详细化。

### ISSUE THREAD

**Issue by chendeshen** [wp-china-yes/update-server#1]
如题。不好意思，可能知识储备不够。不知道自己的操作是否正确。
能否详细以宝塔为例子说明如何部署？

"创建一个站点，将这个PHP脚本)index.php扔上去，之后修改API域名的反向代理的配置文件，添加如下配置即可。"
location ^~ /plugins/update-check/1.1/ {
    proxy_pass  http://your_domain/;
}

例如：
这句应该是加在原本WordPress站点的nginx.conf还是新站点的nginx.conf？
your_domain是原本WordPress站点的URL还是新站点的URL？

**Comment by sunxiyuan** [comment]
这个脚本是留给打算自建仓库源的小伙伴们用的，普通用户可以不用关注的～我维护的源已经部署好这个脚本了，你们可以正常接收到插件的更新推送

**Comment by chendeshen** [comment]
感谢解答。
